backend:
  name: git-gateway
  branch: main
  accept_roles:
  - admin
  - editor
  - author

publish_mode: editorial_workflow

media_folder: "static/media"

collections:
  - name: "blog"
    label: "Blog"
    folder: "blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      # - {label: "Featured Image", name: "thumbnail", widget: "image"}
      # - {label: "Read time (mins)", name: "readtime", widget: "number"}
      - {label: "Body", name: "body", widget: "markdown"}
      # - {label: "Slug", name: "slug", widget: "hidden", default: "blog/{{year}}-{{month}}-{{day}}-{{slug}}"}
